### ISSUE TITLE
Biała stona

### ISSUE THREAD

**Issue by szogi1910** [sloenthran/OnlineShop#1]
Witam
Po instalacji skryptu gdy wchodzimy na adres sklepu pojawia się tylko biała strona bez żadnych błędów

**Comment by sloenthran** [comment]
Proszę otworzyć plik index.php a następnie zakomentować 10 linijkę to jest
"error_reporting(0);" a następnie sprawdzić czy napewno nie występuje żaden
błąd

W dniu 28 stycznia 2018 17:13 użytkownik szogi1910 <notifications@github.com

**Comment by szogi1910** [comment]
Po za komentowaniu nic nie pokazało lecz wymuszenie wyświetlenia błędów już tak 
```
Notice: Undefined index: pages in /home/pggames/domains/onefrag.pl/public_html/sklep/index.php on line 32

Notice: Undefined index: LOGGED in /home/pggames/domains/onefrag.pl/public_html/sklep/index.php on line 37

Fatal error: Uncaught Error: Call to a member function fetch() on boolean in /home/pggames/domains/onefrag.pl/public_html/sklep/application/system/View.php:51 Stack trace: #0 /home/pggames/domains/onefrag.pl/public_html/sklep/model/guest/home.php(9): View->Out() #1 /home/pggames/domains/onefrag.pl/public_html/sklep/index.php(42): require_once('/home/pggames/d...') #2 {main} thrown in /home/pggames/domains/onefrag.pl/public_html/sklep/application/system/View.php on line 51
```

**Comment by szogi1910** [comment]
@sloenthran dasz rade podrzucic jakies podpowiedzi ?

**Comment by sloenthran** [comment]
Da radę podrzucić mi jakiś dostęp do FTP czy coś? Postaram się zobaczyć co
jest grane i w razie czego to poprawię

2018-02-04 16:25 GMT+01:00 szogi1910 <notifications@github.com>:

**Comment by szogi1910** [comment]
@sloenthran Podesłałem na email (gmail)
