### ISSUE TITLE
Biała strona

### ISSUE THREAD

**Issue by VestSmart** [sloenthran/OnlineShop#3]
Witam!
Kiedy w panelu klinkę "Cennik" to wyskakuje biała strona.
![przechwytywanie](https://user-images.githubusercontent.com/24979012/39605231-c99f7b6c-4f2f-11e8-8714-591e7f79b658.JPG)

@sloenthran

**Comment by sloenthran** [comment]
Witaj. Zakomentuj jak możesz error_reporting w index.php i daj znać co Ci
wtedy wyskakuje...

pt., 4 maj 2018 o 00:13 VestSmart <notifications@github.com> napisał(a):

**Comment by VestSmart** [comment]
Nie wiem czy dobrze zrobiłem ale wyskoczyło mi to:
`Fatal error: Call to a member function fetch() on boolean in /usr/home/VestSmart/domains/vestsmart.usermd.net/public_html/onlineshop/model/logged/admin_price.php on line 25`

Używam najnowszej wersji WEB.
@sloenthran 

**EDIT:**
Jeszcze to: (po wpisaniu "error_reporting(E_ALL)")
`Notice: Undefined index: id in /usr/home/VestSmart/domains/vestsmart.usermd.net/public_html/onlineshop/model/logged/admin_price.php on line 6 Notice: Undefined index: action in /usr/home/VestSmart/domains/vestsmart.usermd.net/public_html/onlineshop/model/logged/admin_price.php on line 7 Notice: Undefined variable: Info in /usr/home/VestSmart/domains/vestsmart.usermd.net/public_html/onlineshop/model/logged/admin_price.php on line 21 Fatal error: Call to a member function fetch() on boolean in /usr/home/VestSmart/domains/vestsmart.usermd.net/public_html/onlineshop/model/logged/admin_price.php on line 25`

Używam wersji PHP 5.6

**Comment by sloenthran** [comment]
Co masz w linijkach 23 - 25 w pliku admin_price?

sob., 5 maj 2018 o 13:53 VestSmart <notifications@github.com> napisał(a):

**Comment by sloenthran** [comment]
Zamień linijkę 23 z

			$Query = $MySQL->query("SELECT * FROM `price");

na

			$Query = $MySQL->query("SELECT * FROM `price`");

Być może to przez brak ` wyskakuje Ci ten błąd

**Comment by VestSmart** [comment]
Teraz działa. Dziękuję!
